# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        super-resolution: 1
        super resolution: 1
        image restoration: 1
        upscaling: 1
        supersampling: 1
        optical flow: 1
        temporal consistency: 1
        tempora coherence: 1
        demoireing: 1
        demoire: 1
        frame interpolation: 1
        image quality assessment: 1
        video quality assessment: 1
        deblur: 1
        motion vector: 1

# 通知の閾値
score_threshold: 0
